package core.entities

import java.time.Instant
import java.util.UUID

/**
 * Represents an insight derived from sensor readings.
 * 
 * @param id Unique identifier for the insight (auto-generated by the database)
 * @param macAddress MAC address of the device that generated the reading (references devices.mac_address)
 * @param sensor The sensor ID that identifies the sensor (references sensors.key)
 * @param value The calculated value (e.g., average temperature)
 * @param buildingId Optional reference to the building where the device is located (references buildings.id)
 * @param roomId Optional reference to the room where the device is located (references rooms.id)
 * @param insightTypeId The type of insight (e.g., daily average temperature) (references insight_types.id)
 * @param rangeFrom Start of the time period this insight covers
 * @param rangeTo End of the time period this insight covers
 * @param createdAt When this insight was generated (defaults to current timestamp in database)
 */
final case class Insight(
  id: Option[UUID] = None,
  macAddress: String,
  sensor: String,  // This maps to sensor_id in the database
  value: Double,
  buildingId: Option[UUID] = None,
  roomId: Option[UUID] = None,
  insightTypeId: Option[UUID] = None,
  rangeFrom: Option[Instant] = None,
  rangeTo: Option[Instant] = None,
  createdAt: Instant = Instant.now(),
)
